### ISSUE TITLE
The choice of module names

### ISSUE THREAD

**Issue by magthe** [solidsnack/shell-escape#1]
I have to say that it was a bit surprising that the functions live in `Text.ShellEscape` and _don't_ operate on `Text` but on `ByteString`.

**Comment by solidsnack** [comment]
Maybe it would be reasonable to add overloads for `Text` and leave the `ByteString` implementations where they are? It would be regrettable to break clients. It does seem reasonable that the top-level `Text.*` namespace be taken to refer to "Things having to do with text processing." and not necessarily "Things having to do with the `Text` datatype exclusively.".

**Comment by magthe** [comment]
Arguably `ByteString` isn't really a type for text processing though :)

But I do agree with what you write.

**Comment by solidsnack** [comment]
For generating shell scripts, `ByteString` makes reasonable sense. The operations on `ByteString` and `Text` are more or less the same, and logically belong together; and for the kind of "text" that this is -- source code -- one would expect to operate on `ByteString`s quite often.

**Comment by solidsnack** [comment]
I guess we end up with `class Escape source target` and instances:

``` hs
instance Escape ByteString Bash where ...

instance Escape Text Bash where ...
```

I am a little fuzzy on whether or not Unicode escaping is meaningful to the shell.
